# Generated by Django 3.1.3 on 2021-01-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210125_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingridients',
            field=models.CharField(max_length=4000),
        ),
    ]
